sudo: required
dist: trusty

services:
  - docker

language: node_js

node_js:
  - 8
  - 10

env:
  SKIP_SASS_BINARY_DOWNLOAD_FOR_CI=true
  SKIP_NODE_SASS_TESTS=true

cache:
  yarn: true
  directories:
    - ~/.npm
    - ./node_modules
    - ~/.cache
  override:
    - npm run cy:verify

install:
  - yarn

script:
  - $(npm bin)/print-env CYPRESS
  - yarn test -- --coverage
  - yarn e2e:serve
  - if [ $TRAVIS_BRANCH = 'master' ]; then yarn cy:verify && yarn cy:run; fi

after_success:
  - yarn report-cov

deploy:
  skip_cleanup: true
  provider: script
  script: bash ./deploy-docker.sh
  on:
    branch: master


