language: node_js
sudo: false
dist: trusty
node_js:
  - "9"
  - "8"
  - "7"

cache:
  yarn: true
  directories:
    - "node_modules"

install:
  - yarn

script:
  - yarn test

after_success:
  - yarn run report-cov
