sudo: required
dist: trusty

services:
  - docker

language: node_js

node_js:
  - "8"
  - "10"

env:
  SKIP_SASS_BINARY_DOWNLOAD_FOR_CI=true
  SKIP_NODE_SASS_TESTS=true

cache:
  yarn: true
  directories:
    - ~/.npm
    - ./node_modules
    - ~/.cache
  override:
    - npm run cy:verify

install:
  - yarn

script:
  - yarn test -- --coverage
  - if [ $TRAVIS_PULL_REQUEST = 'false' ]; then yarn e2e:run; fi

after_success:
  - yarn report-cov

deploy:
  skip_cleanup: true
  provider: script
  script: bash ./deploy-docker.sh
  on:
    branch: master


