sudo: required

dist: trusty

services:
  - docker

language: node_js

node_js: '9'

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn

script:
  - yarn test

after_success:
  - yarn report-cov

deploy:
  skip_cleanup: true
  provider: script
  script: chmod +x ./deploy-docker.sh && ./deploy-docker.sh
  on:
    branch: master


