FROM node:9-alpine
MAINTAINER sunnyw <sunnywang@yunify.com>

ENV PATH=$PATH:/app/node_modules/.bin
ENV SASS_BINARY_PATH=/app/build-deps/linux-node-sass-x64-59_binding.node

WORKDIR /app

RUN mkdir -p /app

COPY package.json yarn.lock /tmp/
COPY . /app

RUN cd /tmp \
    && yarn install --pure-lockfile --prefer-offline --verbose \
    && cd /app \
    && ln -fs /tmp/node_modules \
    && yarn prod:build \
    && cd /tmp && rm -rf node_modules \
    && NODE_ENV=production yarn install --pure-lockfile --prod --prefer-offline --verbose \
    && yarn cache clean && rm -rf /app/.cache /app/build-deps

EXPOSE 8000

CMD ["npm", "run", "prod:serve"]


