---
# dashboard global configuration

host: 127.0.0.1
port: 8000

favicon: public/favicon.ico

static:
  /: public
  /locales: src/locales
  development:
    /build: build
  production:
    /dist: dist

apiVersion: v1

# api server
serverUrl: ''

# socket server
socketUrl: 'ws://openpitrix-api-gateway/v1/io'

# socket proxy server
socketProxyHost: 127.0.0.1
socketProxyPort: 9100

# authorization config
clientId: ''
clientSecret: ''

# client side config
app:
  title: OpenPitrix Dashboard

