---
# dashboard global configuration

host: 127.0.0.1
port: 8000

favicon: src/assets/favicon.ico

static:
  /assets: src/assets
  /locales: /locales
  development:
    /build: build
  production:
    /dist: dist

apiVersion: v1

# api server
serverUrl: ''

# socket server
socketUrl: ''

# client side config
app:
  title: 'OpenPitrix Dashboard'
