const session = require('koa-session');
const sessConfig = require('../session-config');

module.exports = app => {
  // secret key generated by python os.urandom
  app.keys = ['\x82\x98\xa5\xf6\xfb'];

  app.use(session(sessConfig, app));

  return async (ctx, next) => {
    // let pv = ctx.session.views || 0;
    // ctx.session.views = ++pv;

    await next();
  };
};
