export Apps from './Apps';
// export AppsInstalled from './Apps/Installed';
export AppDetail from './Apps/Detail';
export AppDeploy from './Apps/Deploy';
export Clusters from './Clusters';
export ClusterDetail from './Clusters/Detail';
export Runtimes from './Runtimes';
export RuntimeAdd from './Runtimes/Add';
export RuntimeDetail from './Runtimes/Detail';
export Repos from './Repos';
export RepoAdd from './Repos/Add';
export RepoDetail from './Repos/Detail';
export Overview from './Overview';
export Categories from './Categories';
export CategoryDetail from './Categories/Detail';
export Roles from './Roles';
export Users from './Users';
